/*
  ____                                   _             _       
 / ___|  ___  _   _ _ __ ___ ___   _ __ | |_   _  __ _(_)_ __  
 \___ \ / _ \| | | | '__/ __/ _ \ | '_ \| | | | |/ _` | | '_ \ 
  ___) | (_) | |_| | | | (_|  __/ | |_) | | |_| | (_| | | | | |
 |____/ \___/ \__,_|_|  \___\___| | .__/|_|\__,_|\__, |_|_| |_|
                                  |_|            |___/         
# A Template for Dump2dbPlugin, a Source Plugin
# Generated by the command: plugin -t source -d . dump2db
# Hostname: Fram-IV-3.local
# Current working directory: /Users/p4010/MASSM/mads
# Creation date: 2026-03-19T14:39:54.425+0100
# NOTICE: MADS Version 2.0.2
*/
// Mandatory included headers
#include <source.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include "csv_loader.hpp"
#include <thread>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "dump2db"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Dump2dbPlugin : public Source<json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: the result only has a copy of _error
  // return_type::critical: execution stops
  return_type get_output(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    json measurements = {};
    bool eof = !_csv_loader->load_line(measurements);
    if (eof) {
      if (_params["repeat"].get<bool>()) {
        _csv_loader->reset();
        return return_type::retry;
      } else {
        _error = "End of CSV file reached and repeat is disabled.";
        cerr << _error << endl;
        return return_type::critical;
      }
    }

    if (_params["what"] == "force") {
      if (measurements.contains("Fx")) {
        out["topic"] = "raw_force";
        measurements.erase("Ax");
        measurements.erase("Ay");
        measurements.erase("Az");
        measurements.erase("microphone");
        out["measurements"] = measurements;
        this_thread::sleep_for(1ms);
        return return_type::success;
      } else {
        return return_type::retry;
      }
    } else if (_params["what"] == "accel") {

      static json acc = {
        {"Ax", json::array()},
        {"Ay", json::array()},
        {"Az", json::array()},
        {"microphone", json::array()}
      };


      acc["Ax"][measurements["idx"].get<int>()] = measurements["Ax"];
      acc["Ay"][measurements["idx"].get<int>()] = measurements["Ay"];
      acc["Az"][measurements["idx"].get<int>()] = measurements["Az"];
      acc["microphone"][measurements["idx"].get<int>()] = measurements["microphone"];
      if (measurements["idx"] < 9) {
        return return_type::retry;
      }

      out["topic"] = "raw_acceleration";
      out["measurements"]["Ax"] = acc["Ax"];
      out["measurements"]["Ay"] = acc["Ay"];
      out["measurements"]["Az"] = acc["Az"];
      out["measurements"]["microphone"] = acc["microphone"];
      out["measurements"]["timestamp"] = measurements["timestamp"];
      out["measurements"]["Time"] = measurements["Time"];
      acc["Ax"].clear();
      acc["Ay"].clear();
      acc["Az"].clear();
      acc["microphone"].clear();
      this_thread::sleep_for(1ms);
      return return_type::success;
    } else {
      _error = string("Unsupported operation: ") + _params["what"].get<string>();
      return return_type::critical;
    }
    throw runtime_error("Unexpected condition!");
  }

  void set_params(const json &params) override {
    Source::set_params(params);
    _params["repeat"] = false;
    _params["what"] = "accel";

    _params.merge_patch(params);
    
    if (!_params.contains("file_path")) {
      throw std::runtime_error("Missing required parameter: file_path");
    }

    _csv_loader = std::make_unique<Mads::CsvLoader>(_params["file_path"].get<std::string>());

  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    return {
      {"file_path", _params["file_path"].get<std::string>()},
      {"dumping", _params["what"].get<string>()}
    };
    
  };

private:
  // Define the fields that are used to store internal resources
  std::unique_ptr<Mads::CsvLoader> _csv_loader;
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_SOURCE_DRIVER(Dump2dbPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  Dump2dbPlugin plugin;
  json output, params;

  // Set example values to params
  params["file_path"] = argv[1];

  // Set the parameters
  plugin.set_params(params);

  // Process data

  while (plugin.get_output(output) == return_type::success) {
    cout << output.dump() << endl;
  }

  return 0;
}
